# Generated by Django 4.2.7 on 2023-12-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('z', 'zero'), ('s', 'studying'), ('p', 'pause'), ('d', 'drop out'), ('g', 'graduated')], default='z', max_length=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='type',
            field=models.CharField(choices=[('main', 'Main'), ('ass', 'Assistent')], default='main', max_length=4),
        ),
    ]
