# Generated by Django 4.2.7 on 2023-12-07 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('honor', models.IntegerField(default=0)),
                ('totalCompleted', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CodewarsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('challengers', models.ManyToManyField(to='codewars.challenger')),
            ],
        ),
        migrations.CreateModel(
            name='Chellange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chellange_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('completedAt', models.DateTimeField()),
                ('slug', models.SlugField()),
                ('chellanger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chellanges', to='codewars.challenger')),
            ],
        ),
    ]
